/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        
        // This is to remove unnecessary warnings from your console
        System.setProperty("java.util.logging.config.file", "logging.properties");
        
        //TestCases tests = new TestCases(); // Initialize your test class
        Automate_frame frame= new Automate_frame();

        //TODO: call your test case functions one after other here

       // tests.testCase01();
        frame.framestext();

        //END Tests


       // tests.endTest(); // End your test by clearning connections and closing browser
       frame.endTest();
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
